# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: storage-api-service
spec:
  selector:
    app: storage-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort   # or LoadBalancer if on cloud
